# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBuyer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_type', models.IntegerField(choices=[(0, '买家'), (1, '卖家')])),
                ('balance', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='余额')),
            ],
        ),
        migrations.CreateModel(
            name='UserSeller',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_type', models.IntegerField(choices=[(0, '买家'), (1, '卖家')])),
                ('sales_amount', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='销售额')),
                ('balance', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='余额')),
            ],
        ),
    ]
