# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-08 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userseller',
            name='balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='userseller',
            name='sales_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='销售额'),
        ),
    ]
