# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181209_1950'),
        ('account', '0002_auto_20181208_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected', models.BooleanField(default=False, verbose_name='添加到收藏')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserBuyer', verbose_name='用户')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item', verbose_name='商品')),
            ],
        ),
    ]
