# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=60, verbose_name='商品名')),
                ('version', models.IntegerField(default=0, verbose_name='版本号')),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='商品价格')),
                ('inventory', models.IntegerField(default=0, verbose_name='库存')),
                ('sales_volume', models.IntegerField(default=0, verbose_name='销售量')),
                ('introductions', models.URLField(verbose_name='介绍地址')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('last_edit', models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserSeller', verbose_name='所有者')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '已创建'), (1, '已支付'), (2, '已发货'), (3, '已完成'), (4, '申请退货'), (5, '已关闭')], default=0, verbose_name='订单状态')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('last_edit', models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间')),
                ('total_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='总金额')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserBuyer', verbose_name='购买者')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='价格')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item', verbose_name='商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='订单')),
            ],
        ),
        migrations.CreateModel(
            name='PictureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.URLField(verbose_name='图片')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ActiveItem', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=20, verbose_name='店铺名')),
                ('sales_volume', models.IntegerField(default=0, verbose_name='销售量')),
                ('sales_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='销售额')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserSeller', verbose_name='所有者')),
            ],
        ),
        migrations.AddField(
            model_name='activeshop',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='店铺'),
        ),
        migrations.AddField(
            model_name='activeitem',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='商品'),
        ),
    ]
