# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-08 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_item_introductions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeitem',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Item', verbose_name='商品'),
        ),
    ]
