# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-08 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181208_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='所属店铺'),
        ),
    ]
