# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-08 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181208_1620'),
        ('shop', '0004_item_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.UserSeller', verbose_name='卖家'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserBuyer', verbose_name='买家'),
        ),
    ]
