# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-08 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181209_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.TextField(default='', max_length=65535, verbose_name='订单详细'),
            preserve_default=False,
        ),
    ]
