# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShopList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitemlist',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitemlist',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=True, verbose_name='活动的'),
        ),
        migrations.DeleteModel(
            name='OrderItemList',
        ),
        migrations.AddField(
            model_name='ordershoplist',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='ordershoplist',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='商店'),
        ),
    ]
